services:
  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    command: >
      sh -c "
      if [ ! -f /app/db.sqlite3 ] || [ -d /app/db.sqlite3 ]; then
        rm -rf /app/db.sqlite3
        touch /app/db.sqlite3
        chmod 644 /app/db.sqlite3
      fi &&
      python manage.py migrate &&
      python populate_db.py &&
      python manage.py runserver 0.0.0.0:8000
      "
    environment:
      PYTHONUNBUFFERED: "1"
      SOCIAL_AUTH_GITHUB_KEY: "Ov23lioS8hkfRe4VgGgZ"
      SOCIAL_AUTH_GITHUB_SECRET: "0e091502836963ceaa3662e1abc2021bdbf092e2"
